### ISSUE TITLE
Lista de palabras en galego

### ISSUE THREAD

**Issue by igonro** [dicgalego/digalegoKINDLE#1]
Boas, sería posible obter un ficheiro de texto cunha lista completa de todas as palabras en galego? Estou traballando nun proxecto, e non atopo unha lista con todas as palabras en galego.

**Comment by nonquerospam2** [comment]
Ola.
Xa non teño acceso a esta conta github.
A ver se che serve esta lista:
https://github.com/nonquerospam2/wordlist_galego
Saúde

**Comment by igonro** [comment]
Moitas gracias! @nonquerospam2
